# <font color = 'red'>1. <u>One Hot Encoding - from Scratch</u></font>

In [39]:
import pandas as pd
from nltk.tokenize import word_tokenize, sent_tokenize

text = 'GeeksForGeeks is not a website or a company. GeeksForGeeks is a coding environment. Thats why I love it. Which is good not bad at all.'
text

'GeeksForGeeks is not a website or a company. GeeksForGeeks is a coding environment. Thats why I love it. Which is good not bad at all.'

## 1.1 Finding the sequence

In [40]:
seq = set()

for word in word_tokenize(text):
    if word != '.':
        seq.add(word)
        
seq = list(seq)
print(seq)

['environment', 'GeeksForGeeks', 'good', 'at', 'all', 'is', 'Thats', 'or', 'not', 'bad', 'a', 'website', 'I', 'love', 'company', 'it', 'Which', 'why', 'coding']


In [41]:
seq.index('GeeksForGeeks')

1

## 1.2 Finding index to encode

In [44]:
data = []

for sent in sent_tokenize(text):

    index = []
    
    for word in word_tokenize(sent):
        
        if word != '.':
            index.append(seq.index(word))
            print(word, end = ' ')
    
    print('\n', index, '\n')
    data.append(index)

GeeksForGeeks is not a website or a company 
 [1, 5, 8, 10, 11, 7, 10, 14] 

GeeksForGeeks is a coding environment 
 [1, 5, 10, 18, 0] 

Thats why I love it 
 [6, 17, 12, 13, 15] 

Which is good not bad at all 
 [16, 5, 2, 8, 9, 3, 4] 



## 1.3 Encode the sentance in One hot Encoding format

In [27]:
fin = []

for indexes in data:
    enc = [0 for x in range(len(seq))]
    for index in indexes:
        enc[index] = 1
    fin.append(enc)

In [28]:
fin

[[0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0],
 [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]]

In [ ]:
[1, 5, 8, 10, 11, 7, 10, 14]
[0,1,0,0,0,1,0,0,1,0,1,1,0,0,1,0,0,0,0] = 'GeeksForGeeks is not a website or a company '

## 1.4 Creating the DataFrame

In [32]:
df = pd.DataFrame(fin, columns = seq)
df['Sentances_'] = sent_tokenize(text)
df

environment  GeeksForGeeks  good  at  all  is  Thats  or  not  bad  a  \
0            0              1     0   0    0   1      0   1    1    0  1   
1            1              1     0   0    0   1      0   0    0    0  1   
2            0              0     0   0    0   0      1   0    0    0  0   
3            0              0     1   1    1   1      0   0    1    1  0   

   website  I  love  company  it  Which  why  coding  \
0        1  0     0        1   0      0    0       0   
1        0  0     0        0   0      0    0       1   
2        0  1     1        0   1      0    1       0   
3        0  0     0        0   0      1    0       0   

                                     Sentances_  
0  GeeksForGeeks is not a website or a company.  
1        GeeksForGeeks is a coding environment.  
2                          Thats why I love it.  
3                 Which is good not bad at all.

# <font color = 'red'>2. <u>One Hot Encoding - with sklearn</u></font>

## 1.1 One word at a time

In [36]:
import pandas as pd

text = ['cat', 'dog', 'fish', 'bird', 'cat', 'dog']

data = pd.get_dummies(text)
data

bird  cat  dog  fish
0     0    1    0     0
1     0    0    1     0
2     0    0    0     1
3     1    0    0     0
4     0    1    0     0
5     0    0    1     0

## 1.2 Whole sentance at a time

In [30]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder

text = ['i love dogs', 'i hate cats', 'i like turtles', 'i love the dogs']

text = np.reshape(text, (-1,1))

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)
print(one_hot.toarray())
print([i[3:] for i in encoder.get_feature_names()])

[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['i hate cats', 'i like turtles', 'i love dogs', 'i love the dogs']


## Tokenized Sentance

In [57]:
from sklearn.preprocessing import OneHotEncoder

text = [['this', 'is', 'good'], ['but', 'its', 'fine']]

encoder = OneHotEncoder()
encoder.fit(text)

one_hot = encoder.transform(text)

print(one_hot.data)
print('\n', one_hot.toarray(), '\n')

print([i[3:] for i in encoder.get_feature_names()])

[1. 1. 1. 1. 1. 1.]

 [[0. 1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1. 0.]] 

['but', 'this', 'is', 'its', 'fine', 'good']


In [64]:
pd.DataFrame(one_hot.toarray(), columns=[i[3:] for i in encoder.get_feature_names()])

but  this   is  its  fine  good
0  0.0   1.0  1.0  0.0   0.0   1.0
1  1.0   0.0  0.0  1.0   1.0   0.0